<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="0" skipped="1" tests="9" time="114.500" timestamp="2021-03-01T18:00:27.678804" hostname="pragmatic"><testcase classname="authentication.tests.test_backend" name="test_backend_access_inactive_user_exception" time="7.915" /><testcase classname="authentication.tests.test_backend" name="test_backend_access_inactive_user" time="0.029" /><testcase classname="authentication.tests.test_backend" name="test_backend_access_inactive_user_with_employer_role" time="0.034" /><testcase classname="authentication.tests.test_backend" name="test_backend_with_wrong_auth_credentials" time="0.028" /><testcase classname="authentication.tests.test_backend" name="test_backend_access_active_user_exception_on_protected_endpoint" time="0.027" /><testcase classname="authentication.tests.test_backend" name="test_backend_success" time="0.026" /><testcase classname="authentication.tests.test_backend" name="test_backend_success_token" time="0.027" /><testcase classname="authentication.tests.test_login_api" name="test_login_inactive_user" time="0.028" /><testcase classname="authentication.tests.test_login_api" name="test_login_active_user" time="0.046"><skipped type="pytest.xfail" message="" /></testcase><testcase time="0.005" /></testsuite></testsuites>